---
excluded_paths:
  globally:
  - "Godeps"
  - "vendor"
  - "staging"
  - ".git"
  - ".github"
  by_reviewer:
  - reviewer:
    paths:
review_agreements:
- reviewer: silasbw
  paths: /
- reviewer: jasonbrooks
  paths: /
- reviewer: aledbf
  paths: /
- reviewer: louis-paul
  paths: /
- reviewer: jasonbrooks
  paths: /
- reviewer: ingvagabund
  paths: /
- reviewer: rutsky
  paths: /
